---
- name: Install the postgresql94 repository on {{ ansible_hostname }}
  command: yum -y install '{{ postgresql94_repo_rpm_url }}'

- name: Install packages on {{ ansible_hostname }}
  yum:
    name: '{{ item }}'
    state: latest
  with_items: '{{ install_packages }}'
