---
- name: Install the postgresql94 repository on {{ ansible.hostname }}
  command: yum -y install '{{ postgresql94_repo_rpm }}'

- name: Install packages
  yum:
    name: '{{ postgresql94_rpm }}'
    state: latest
  with_itmes: '{{ install_packages }}'
